// GENERATED by tools/gen_preflop_ranks.cpp -- do not edit by hand.
//
// The 169 starting-hand classes ordered by equity against a random hand,
// measured with this repo's own simulator at 50000 trials per class (standard
// error ~0.0022, well inside the gaps that matter for ordering).
//
// Used to build an opponent range: taking entries in order until the
// cumulative combo count reaches the wanted fraction of 1326 gives the
// "top X%" of hands.

#ifndef POKERCPP_PREFLOP_RANKS_H
#define POKERCPP_PREFLOP_RANKS_H

namespace chipzen {

struct PreflopClass {
    int high;      // 2-14
    int low;       // 2-14
    bool suited;
    int combos;    // 6 pair, 4 suited, 12 offsuit
};

// Descending by equity vs a random hand. Combos sum to 1326.
inline constexpr PreflopClass kPreflopRanked[169] = {
    {14, 14, false,  6},  // AA   eq 0.8522  cum    6
    {13, 13, false,  6},  // KK   eq 0.8237  cum   12
    {12, 12, false,  6},  // QQ   eq 0.8001  cum   18
    {11, 11, false,  6},  // JJ   eq 0.7775  cum   24
    {10, 10, false,  6},  // TT   eq 0.7479  cum   30
    { 9,  9, false,  6},  // 99   eq 0.7189  cum   36
    { 8,  8, false,  6},  // 88   eq 0.6914  cum   42
    {14, 13, true ,  4},  // AKs  eq 0.6717  cum   46
    {14, 12, true ,  4},  // AQs  eq 0.6624  cum   50
    { 7,  7, false,  6},  // 77   eq 0.6585  cum   56
    {14, 11, true ,  4},  // AJs  eq 0.6557  cum   60
    {14, 13, false, 12},  // AKo  eq 0.6497  cum   72
    {14, 10, true ,  4},  // ATs  eq 0.6464  cum   76
    {14, 12, false, 12},  // AQo  eq 0.6461  cum   88
    {14, 11, false, 12},  // AJo  eq 0.6374  cum  100
    {13, 12, true ,  4},  // KQs  eq 0.6374  cum  104
    { 6,  6, false,  6},  // 66   eq 0.6335  cum  110
    {14,  9, true ,  4},  // A9s  eq 0.6276  cum  114
    {14, 10, false, 12},  // ATo  eq 0.6270  cum  126
    {13, 11, true ,  4},  // KJs  eq 0.6257  cum  130
    {13, 12, false, 12},  // KQo  eq 0.6164  cum  142
    {14,  8, true ,  4},  // A8s  eq 0.6164  cum  146
    {13, 10, true ,  4},  // KTs  eq 0.6160  cum  150
    {14,  7, true ,  4},  // A7s  eq 0.6114  cum  154
    {14,  9, false, 12},  // A9o  eq 0.6101  cum  166
    {13, 11, false, 12},  // KJo  eq 0.6053  cum  178
    { 5,  5, false,  6},  // 55   eq 0.6037  cum  184
    {14,  5, true ,  4},  // A5s  eq 0.6028  cum  188
    {13,  9, true ,  4},  // K9s  eq 0.6027  cum  192
    {12, 11, true ,  4},  // QJs  eq 0.6015  cum  196
    {14,  6, true ,  4},  // A6s  eq 0.6013  cum  200
    {13, 10, false, 12},  // KTo  eq 0.5975  cum  212
    {14,  8, false, 12},  // A8o  eq 0.5973  cum  224
    {12, 10, true ,  4},  // QTs  eq 0.5949  cum  228
    {14,  4, true ,  4},  // A4s  eq 0.5920  cum  232
    {14,  7, false, 12},  // A7o  eq 0.5887  cum  244
    {14,  3, true ,  4},  // A3s  eq 0.5826  cum  248
    {13,  8, true ,  4},  // K8s  eq 0.5818  cum  252
    {12,  9, true ,  4},  // Q9s  eq 0.5816  cum  256
    {14,  5, false, 12},  // A5o  eq 0.5803  cum  268
    {13,  9, false, 12},  // K9o  eq 0.5788  cum  280
    {12, 11, false, 12},  // QJo  eq 0.5777  cum  292
    {14,  6, false, 12},  // A6o  eq 0.5765  cum  304
    {13,  7, true ,  4},  // K7s  eq 0.5763  cum  308
    {11, 10, true ,  4},  // JTs  eq 0.5762  cum  312
    {14,  2, true ,  4},  // A2s  eq 0.5720  cum  316
    {12, 10, false, 12},  // QTo  eq 0.5715  cum  328
    {14,  4, false, 12},  // A4o  eq 0.5700  cum  340
    { 4,  4, false,  6},  // 44   eq 0.5685  cum  346
    {13,  6, true ,  4},  // K6s  eq 0.5607  cum  350
    {13,  8, false, 12},  // K8o  eq 0.5595  cum  362
    {13,  5, true ,  4},  // K5s  eq 0.5595  cum  366
    {12,  8, true ,  4},  // Q8s  eq 0.5592  cum  370
    {11,  9, true ,  4},  // J9s  eq 0.5573  cum  374
    {14,  3, false, 12},  // A3o  eq 0.5569  cum  386
    {13,  7, false, 12},  // K7o  eq 0.5540  cum  398
    {11, 10, false, 12},  // JTo  eq 0.5516  cum  410
    {12,  9, false, 12},  // Q9o  eq 0.5504  cum  422
    {14,  2, false, 12},  // A2o  eq 0.5500  cum  434
    {13,  4, true ,  4},  // K4s  eq 0.5443  cum  438
    {12,  7, true ,  4},  // Q7s  eq 0.5428  cum  442
    {11,  8, true ,  4},  // J8s  eq 0.5423  cum  446
    {13,  6, false, 12},  // K6o  eq 0.5420  cum  458
    {13,  3, true ,  4},  // K3s  eq 0.5412  cum  462
    {10,  9, true ,  4},  // T9s  eq 0.5400  cum  466
    {12,  8, false, 12},  // Q8o  eq 0.5384  cum  478
    { 3,  3, false,  6},  // 33   eq 0.5381  cum  484
    {12,  6, true ,  4},  // Q6s  eq 0.5346  cum  488
    {11,  9, false, 12},  // J9o  eq 0.5318  cum  500
    {13,  5, false, 12},  // K5o  eq 0.5317  cum  512
    {13,  2, true ,  4},  // K2s  eq 0.5292  cum  516
    {12,  5, true ,  4},  // Q5s  eq 0.5278  cum  520
    {11,  7, true ,  4},  // J7s  eq 0.5260  cum  524
    {10,  8, true ,  4},  // T8s  eq 0.5222  cum  528
    {13,  4, false, 12},  // K4o  eq 0.5194  cum  540
    {12,  7, false, 12},  // Q7o  eq 0.5192  cum  552
    {12,  4, true ,  4},  // Q4s  eq 0.5190  cum  556
    {12,  6, false, 12},  // Q6o  eq 0.5165  cum  568
    {11,  8, false, 12},  // J8o  eq 0.5161  cum  580
    {13,  3, false, 12},  // K3o  eq 0.5126  cum  592
    {10,  9, false, 12},  // T9o  eq 0.5126  cum  604
    {12,  3, true ,  4},  // Q3s  eq 0.5081  cum  608
    {13,  2, false, 12},  // K2o  eq 0.5064  cum  620
    {11,  6, true ,  4},  // J6s  eq 0.5062  cum  624
    {10,  7, true ,  4},  // T7s  eq 0.5061  cum  628
    { 9,  8, true ,  4},  // 98s  eq 0.5034  cum  632
    { 2,  2, false,  6},  // 22   eq 0.5032  cum  638
    {12,  2, true ,  4},  // Q2s  eq 0.5000  cum  642
    {11,  5, true ,  4},  // J5s  eq 0.4982  cum  646
    {10,  8, false, 12},  // T8o  eq 0.4976  cum  658
    {11,  7, false, 12},  // J7o  eq 0.4954  cum  670
    {12,  5, false, 12},  // Q5o  eq 0.4950  cum  682
    {12,  4, false, 12},  // Q4o  eq 0.4920  cum  694
    {11,  4, true ,  4},  // J4s  eq 0.4909  cum  698
    {10,  6, true ,  4},  // T6s  eq 0.4881  cum  702
    { 9,  7, true ,  4},  // 97s  eq 0.4879  cum  706
    {10,  7, false, 12},  // T7o  eq 0.4809  cum  718
    {12,  3, false, 12},  // Q3o  eq 0.4802  cum  730
    { 9,  8, false, 12},  // 98o  eq 0.4783  cum  742
    {11,  3, true ,  4},  // J3s  eq 0.4780  cum  746
    {11,  6, false, 12},  // J6o  eq 0.4774  cum  758
    {12,  2, false, 12},  // Q2o  eq 0.4769  cum  770
    { 8,  7, true ,  4},  // 87s  eq 0.4760  cum  774
    { 9,  6, true ,  4},  // 96s  eq 0.4738  cum  778
    {11,  2, true ,  4},  // J2s  eq 0.4734  cum  782
    {11,  5, false, 12},  // J5o  eq 0.4732  cum  794
    {10,  5, true ,  4},  // T5s  eq 0.4684  cum  798
    { 8,  6, true ,  4},  // 86s  eq 0.4660  cum  802
    {10,  4, true ,  4},  // T4s  eq 0.4641  cum  806
    {11,  4, false, 12},  // J4o  eq 0.4623  cum  818
    { 9,  7, false, 12},  // 97o  eq 0.4616  cum  830
    {10,  6, false, 12},  // T6o  eq 0.4612  cum  842
    {10,  3, true ,  4},  // T3s  eq 0.4568  cum  846
    { 9,  5, true ,  4},  // 95s  eq 0.4565  cum  850
    {11,  3, false, 12},  // J3o  eq 0.4541  cum  862
    { 8,  7, false, 12},  // 87o  eq 0.4524  cum  874
    { 7,  6, true ,  4},  // 76s  eq 0.4518  cum  878
    {10,  2, true ,  4},  // T2s  eq 0.4500  cum  882
    {11,  2, false, 12},  // J2o  eq 0.4433  cum  894
    { 9,  6, false, 12},  // 96o  eq 0.4427  cum  906
    { 8,  5, true ,  4},  // 85s  eq 0.4426  cum  910
    {10,  5, false, 12},  // T5o  eq 0.4409  cum  922
    { 9,  4, true ,  4},  // 94s  eq 0.4399  cum  926
    { 7,  5, true ,  4},  // 75s  eq 0.4393  cum  930
    {10,  4, false, 12},  // T4o  eq 0.4362  cum  942
    { 9,  3, true ,  4},  // 93s  eq 0.4341  cum  946
    { 8,  6, false, 12},  // 86o  eq 0.4329  cum  958
    { 8,  4, true ,  4},  // 84s  eq 0.4311  cum  962
    {10,  3, false, 12},  // T3o  eq 0.4301  cum  974
    { 6,  5, true ,  4},  // 65s  eq 0.4300  cum  978
    { 9,  5, false, 12},  // 95o  eq 0.4262  cum  990
    { 7,  6, false, 12},  // 76o  eq 0.4237  cum 1002
    { 9,  2, true ,  4},  // 92s  eq 0.4235  cum 1006
    { 7,  4, true ,  4},  // 74s  eq 0.4187  cum 1010
    { 6,  4, true ,  4},  // 64s  eq 0.4158  cum 1014
    {10,  2, false, 12},  // T2o  eq 0.4156  cum 1026
    { 8,  5, false, 12},  // 85o  eq 0.4147  cum 1038
    { 5,  4, true ,  4},  // 54s  eq 0.4132  cum 1042
    { 8,  3, true ,  4},  // 83s  eq 0.4102  cum 1046
    { 9,  4, false, 12},  // 94o  eq 0.4070  cum 1058
    { 7,  5, false, 12},  // 75o  eq 0.4058  cum 1070
    { 9,  3, false, 12},  // 93o  eq 0.4055  cum 1082
    { 7,  3, true ,  4},  // 73s  eq 0.4025  cum 1086
    { 8,  2, true ,  4},  // 82s  eq 0.4024  cum 1090
    { 6,  5, false, 12},  // 65o  eq 0.3975  cum 1102
    { 8,  4, false, 12},  // 84o  eq 0.3956  cum 1114
    { 5,  3, true ,  4},  // 53s  eq 0.3954  cum 1118
    { 6,  3, true ,  4},  // 63s  eq 0.3891  cum 1122
    { 9,  2, false, 12},  // 92o  eq 0.3891  cum 1134
    { 4,  3, true ,  4},  // 43s  eq 0.3855  cum 1138
    { 5,  4, false, 12},  // 54o  eq 0.3822  cum 1150
    { 6,  4, false, 12},  // 64o  eq 0.3815  cum 1162
    { 7,  4, false, 12},  // 74o  eq 0.3811  cum 1174
    { 7,  2, true ,  4},  // 72s  eq 0.3804  cum 1178
    { 5,  2, true ,  4},  // 52s  eq 0.3770  cum 1182
    { 6,  2, true ,  4},  // 62s  eq 0.3767  cum 1186
    { 8,  3, false, 12},  // 83o  eq 0.3722  cum 1198
    { 4,  2, true ,  4},  // 42s  eq 0.3697  cum 1202
    { 7,  3, false, 12},  // 73o  eq 0.3657  cum 1214
    { 5,  3, false, 12},  // 53o  eq 0.3652  cum 1226
    { 8,  2, false, 12},  // 82o  eq 0.3651  cum 1238
    { 3,  2, true ,  4},  // 32s  eq 0.3581  cum 1242
    { 6,  3, false, 12},  // 63o  eq 0.3573  cum 1254
    { 4,  3, false, 12},  // 43o  eq 0.3520  cum 1266
    { 7,  2, false, 12},  // 72o  eq 0.3426  cum 1278
    { 5,  2, false, 12},  // 52o  eq 0.3412  cum 1290
    { 6,  2, false, 12},  // 62o  eq 0.3397  cum 1302
    { 4,  2, false, 12},  // 42o  eq 0.3345  cum 1314
    { 3,  2, false, 12},  // 32o  eq 0.3199  cum 1326
};

} // namespace chipzen

#endif
