// Generates montecarlo/preflop_ranks.h: the 169 starting-hand classes ordered
// by equity against a random hand, computed with this repo's own simulator.
#include "../montecarlo/MonteCarloSimulator.h"
#include <algorithm>
#include <cstdio>
#include <vector>
#include <cmath>
#include <cstdlib>
#include <string>
//   g++ -std=c++17 -O2 -o gen tools/gen_preflop_ranks.cpp \
//       montecarlo/MonteCarloSimulator.cpp model/advanced_hand_evaluator.cpp \
//       model/card.cpp model/deck.cpp
//   ./gen 50000 > montecarlo/preflop_ranks.h
int main(int argc, char** argv) {
    int sims = argc > 1 ? atoi(argv[1]) : 50000;
    struct Row { int hi, lo; bool suited; double eq; int combos; };
    std::vector<Row> rows;
    for (int a = 2; a <= 14; ++a) {
        for (int b = 2; b <= a; ++b) {
            for (int s = 0; s < 2; ++s) {
                bool suited = (s == 1);
                if (a == b && suited) continue;          // no suited pairs
                std::vector<Card> hole{
                    Card(static_cast<Rank>(a), Suit::Spades),
                    Card(static_cast<Rank>(b), suited ? Suit::Spades : Suit::Hearts)};
                MonteCarloSimulator sim(hole, {}, sims);
                sim.runSimulation();
                int combos = (a == b) ? 6 : (suited ? 4 : 12);
                rows.push_back({a, b, suited, sim.getEquity(), combos});
            }
        }
    }
    std::sort(rows.begin(), rows.end(), [](const Row& x, const Row& y){ return x.eq > y.eq; });

    printf("// GENERATED by tools/gen_preflop_ranks.cpp -- do not edit by hand.\n");
    printf("//\n// The 169 starting-hand classes ordered by equity against a random hand,\n");
    printf("// measured with this repo's own simulator at %d trials per class (standard\n", sims);
    printf("// error ~%.4f, well inside the gaps that matter for ordering).\n//\n", 0.5/ (double)sqrt((double)sims));
    printf("// Used to build an opponent range: taking entries in order until the\n");
    printf("// cumulative combo count reaches the wanted fraction of 1326 gives the\n");
    printf("// \"top X%%\" of hands.\n\n");
    printf("#ifndef CHIPZEN_PREFLOP_RANKS_H\n#define CHIPZEN_PREFLOP_RANKS_H\n\n");
    printf("namespace chipzen {\n\n");
    printf("struct PreflopClass {\n    int high;      // 2-14\n    int low;       // 2-14\n    bool suited;\n    int combos;    // 6 pair, 4 suited, 12 offsuit\n};\n\n");
    printf("// Descending by equity vs a random hand. Combos sum to 1326.\n");
    printf("inline constexpr PreflopClass kPreflopRanked[169] = {\n");
    const char* R = "..23456789TJQKA";
    int total = 0;
    for (size_t i = 0; i < rows.size(); ++i) {
        const Row& r = rows[i];
        total += r.combos;
        printf("    {%2d, %2d, %-5s, %2d},  // %c%c%-2s eq %.4f  cum %4d\n",
               r.hi, r.lo, r.suited ? "true" : "false", r.combos,
               R[r.hi], R[r.lo], r.hi == r.lo ? "" : (r.suited ? "s" : "o"),
               r.eq, total);
    }
    printf("};\n\n} // namespace chipzen\n\n#endif\n");
    fprintf(stderr, "total combos: %d (expect 1326), classes: %zu\n", total, rows.size());
    return 0;
}
